### ISSUE TITLE
Clustering evidence - OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by shauryr** [allenai/TOPICAL#17]
Hello TOPICAL Team,

Thank you for sharing this is amazing work :) The repo is well organized and easy to follow. 

I was trying out the tool, and I got a CUDA OOM error.

![image](https://github.com/allenai/TOPICAL/assets/12604876/6584ef4d-46b8-4f24-89d9-a32882f2b0a5)

https://github.com/allenai/TOPICAL/blob/7ca4f5ac1e164a60269a7cd49e54a35f9fc80f8b/src/topical/app.py#L142

most probably this can be resolved by -

- Optionally clear cache after processing
```python
torch.cuda.empty_cache()  
```

**Comment by JohnGiorgi** [comment]
Hey @shauryr! Nice to bump into you again here. This issue should be fixed now, please try the demo again and let us know if anything else breaks :)

**Comment by shauryr** [comment]
hi @JohnGiorgi :) It seems like it is working now. Thanks!
